apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: probes
    app: do100-probes
  name: probes
spec:
  containers:
  - image: quay.io/redhattraining/do100-probes:external
    name: probes
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
