apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: do100-probes
  name: do100-probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: do100-probes
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: do100-probes
    spec:
      containers:
      - image: quay.io/redhattraining/do100-probes:external
        name: do100-probes
        resources: {}
status: {}
